# Shap variance penalty

[![open in colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ing-bank/probatus/blob/master/docs/tutorials/shap_rfe_variance_penalty_and_results_comparison.ipynb)

When ShapRFECV is computing feature importance and subsequently eliminating features, it computes the average of shap values to get an estimate of that feature's overall importance. In some situations, the variance of these shap values might be high - which might indicate a lack of agreement regarding that feature's importance. Catering to this situation, probatus allows you to penalize features that have a higher variance of shap values.

By setting `shap_variance_penalty_factor` param within `fit_compute()` method, the averaging of shap values is computed by:
<<add>>

See example below:

In [1]:
%%capture
!pip install probatus
!pip install xgboost

In [2]:
from probatus.features import ShapRFECV
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
import numpy as np
import pandas as pd

In [3]:
X, y = make_classification(n_samples=500, n_informative=20, n_features=100)
model = XGBClassifier(n_estimators=100)
shap_elimination = ShapRFECV(model=model, step=0.2, min_features_to_select=5, cv=5, scoring="f1", n_jobs=5, verbose=1)
report_with_penalty = shap_elimination.fit_compute(X, y, shap_variance_penalty_factor=1.0)

Feature Elimination:   0%|          | 0/95 [00:00<?, ?it/s]

In [4]:
report_without_penalty = shap_elimination.fit_compute(X, y, shap_variance_penalty_factor=0)

Feature Elimination:   0%|          | 0/95 [00:00<?, ?it/s]

In [5]:
report_with_penalty

,num_features,features_set,eliminated_features,train_metric_mean,train_metric_std,val_metric_mean,val_metric_std
1,100,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 3...",1.0,0.0,0.809201,0.028176
2,80,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[55, 54, 53, 52, 51, 50, 48, 21, 47, 46, 26, 2...",1.0,0.0,0.789405,0.023543
3,64,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[19, 20, 49, 56, 57, 58, 59, 60, 61, 62, 63, 97]",1.0,0.0,0.765996,0.045519
4,52,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[15, 16, 17, 18, 64, 65, 66, 67, 68, 96]",1.0,0.0,0.704310,0.017028
5,42,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[12, 13, 14, 69, 70, 71, 72, 95]",1.0,0.0,0.682433,0.014342
6,34,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 73, 74,...","[6, 5, 4, 3, 2, 94]",1.0,0.0,0.653069,0.035080
7,28,"[0, 1, 7, 8, 9, 10, 11, 73, 74, 75, 76, 77, 78...","[10, 9, 8, 7, 93]",1.0,0.0,0.647855,0.024186
8,23,"[0, 1, 11, 73, 74, 75, 76, 77, 78, 79, 80, 81,...","[74, 73, 11, 92]",1.0,0.0,0.615326,0.037546
9,19,"[0, 1, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,...","[76, 75, 91]",1.0,0.0,0.568405,0.068330
10,16,"[0, 1, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,...","[88, 89, 90]",1.0,0.0,0.544659,0.039946
11,13,"[0, 1, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,...","[86, 87]",1.0,0.0,0.524867,0.042913
12,11,"[0, 1, 77, 78, 79, 80, 81, 82, 83, 84, 85]","[84, 85]",1.0,0.0,0.491606,0.050741
13,9,"[0, 1, 77, 78, 79, 80, 81, 82, 83]",[83],1.0,0.0,0.466892,0.040736
14,8,"[0, 1, 77, 78, 79, 80, 81, 82]",[82],1.0,0.0,0.493600,0.031243
15,7,"[0, 1, 77, 78, 79, 80, 81]",[81],1.0,0.0,0.490432,0.031267
16,6,"[0, 1, 77, 78, 79, 80]",[80],1.0,0.0,0.495030,0.045593
17,5,"[0, 1, 77, 78, 79]",[],1.0,0.0,0.514079,0.054683

In [6]:
report_without_penalty

,num_features,features_set,eliminated_features,train_metric_mean,train_metric_std,val_metric_mean,val_metric_std
1,100,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 3...",1.0,0.0,0.809201,0.028176
2,80,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[55, 54, 53, 52, 51, 50, 48, 21, 47, 46, 26, 2...",1.0,0.0,0.789405,0.023543
3,64,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[19, 20, 49, 56, 57, 58, 59, 60, 61, 62, 63, 97]",1.0,0.0,0.765996,0.045519
4,52,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[15, 16, 17, 18, 64, 65, 66, 67, 68, 96]",1.0,0.0,0.704310,0.017028
5,42,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[12, 13, 14, 69, 70, 71, 72, 95]",1.0,0.0,0.682433,0.014342
6,34,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 73, 74,...","[6, 5, 4, 3, 2, 94]",1.0,0.0,0.653069,0.035080
7,28,"[0, 1, 7, 8, 9, 10, 11, 73, 74, 75, 76, 77, 78...","[10, 9, 8, 7, 93]",1.0,0.0,0.647855,0.024186
8,23,"[0, 1, 11, 73, 74, 75, 76, 77, 78, 79, 80, 81,...","[74, 73, 11, 92]",1.0,0.0,0.615326,0.037546
9,19,"[0, 1, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,...","[76, 75, 91]",1.0,0.0,0.568405,0.068330
10,16,"[0, 1, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,...","[88, 89, 90]",1.0,0.0,0.544659,0.039946
11,13,"[0, 1, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,...","[86, 87]",1.0,0.0,0.524867,0.042913
12,11,"[0, 1, 77, 78, 79, 80, 81, 82, 83, 84, 85]","[84, 85]",1.0,0.0,0.491606,0.050741
13,9,"[0, 1, 77, 78, 79, 80, 81, 82, 83]",[83],1.0,0.0,0.466892,0.040736
14,8,"[0, 1, 77, 78, 79, 80, 81, 82]",[82],1.0,0.0,0.493600,0.031243
15,7,"[0, 1, 77, 78, 79, 80, 81]",[81],1.0,0.0,0.490432,0.031267
16,6,"[0, 1, 77, 78, 79, 80]",[80],1.0,0.0,0.495030,0.045593
17,5,"[0, 1, 77, 78, 79]",[],1.0,0.0,0.514079,0.054683

# Which approach is better?

Let's compare a few different configurations of RFECV.

In [7]:
# Compare A: shap_variance_penalty_factor=0.5 & approximate=True
# vs B: shap_variance_penalty_factor=0 (disabled) & approximate=True
num_simulations = 5
results = []


def get_best_idx(shap_report):
    shap_report["eval_metric"] = shap_report["val_metric_mean"]
    best_iteration_idx = shap_report["eval_metric"].argmax()

    return best_iteration_idx


for i in range(num_simulations):
    # Params
    n_samples = np.random.randint(100, 500)
    n_features = 200
    n_informative = np.random.randint(10, 200)
    test_size = np.random.uniform(0.05, 0.5)

    # Create data
    X, y = make_classification(n_samples=n_samples, n_informative=n_informative, n_features=n_features)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
    X_train = pd.DataFrame(X_train)
    X_test = pd.DataFrame(X_test)

    # Model
    model = XGBClassifier(n_estimators=100)

    # Best score from ShapRFECV WITHOUT penalization
    shap_elimination = ShapRFECV(
        model=model, step=0.2, min_features_to_select=5, cv=5, scoring="f1", n_jobs=5, verbose=1
    )
    report_a = shap_elimination.fit_compute(
        X_train, y_train, shap_variance_penalty_factor=0, approximate=True, check_additivity=False
    )
    best_idx_a = get_best_idx(report_a)
    best_score_a = report_a["val_metric_mean"].iloc[best_idx_a]
    std_a = report_a["val_metric_std"].iloc[best_idx_a]
    num_features_a = report_a["num_features"].iloc[best_idx_a]

    # Best score from ShapRFECV WITH penalization
    shap_elimination = ShapRFECV(
        model=model, step=0.2, min_features_to_select=5, cv=5, scoring="f1", n_jobs=5, verbose=1
    )
    report_b = shap_elimination.fit_compute(
        X_train, y_train, shap_variance_penalty_factor=0.5, approximate=True, check_additivity=False
    )
    best_idx_b = get_best_idx(report_b)
    best_score_b = report_b["val_metric_mean"].iloc[best_idx_b]
    std_b = report_b["val_metric_std"].iloc[best_idx_b]
    num_features_b = report_b["num_features"].iloc[best_idx_b]

    results.append(
        [best_score_a, std_a, num_features_a, best_score_b, std_b, num_features_b, n_samples, n_features, n_informative]
    )

    results_df = pd.DataFrame(
        results,
        columns=[
            "best_score_a",
            "std_a",
            "num_features_a",
            "best_score_b",
            "std_b",
            "num_features_b",
            "n_samples",
            "n_features",
            "n_informative",
        ],
    )

# Show results
results_df

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

,best_score_a,std_a,num_features_a,best_score_b,std_b,num_features_b,n_samples,n_features,n_informative
0,0.727565,0.083661,200,0.727565,0.083661,200,321,200,56
1,0.602625,0.049179,13,0.602625,0.049179,13,220,200,109
2,0.630941,0.051562,200,0.630941,0.051562,200,295,200,195
3,0.681592,0.105120,83,0.681592,0.105120,83,421,200,130
4,0.670626,0.042045,160,0.670626,0.042045,160,366,200,146

In [8]:
# Compare A: shap_variance_penalty_factor=0.5 & approximate=False
# vs B: shap_variance_penalty_factor=0 (disabled) & approximate=False
num_simulations = 5
results = []

for i in range(num_simulations):
    # Params
    n_samples = np.random.randint(100, 500)
    n_features = 200
    n_informative = np.random.randint(10, 200)
    test_size = np.random.uniform(0.05, 0.5)

    # Create data
    X, y = make_classification(n_samples=n_samples, n_informative=n_informative, n_features=n_features)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
    X_train = pd.DataFrame(X_train)
    X_test = pd.DataFrame(X_test)

    # Model
    model = XGBClassifier(n_estimators=100)

    # Best score from ShapRFECV WITHOUT penalization
    shap_elimination = ShapRFECV(
        model=model, step=0.2, min_features_to_select=5, cv=5, scoring="f1", n_jobs=5, verbose=1
    )
    report_a = shap_elimination.fit_compute(X_train, y_train, shap_variance_penalty_factor=0, approximate=False)
    best_idx_a = get_best_idx(report_a)
    best_score_a = report_a["val_metric_mean"].iloc[best_idx_a]
    std_a = report_a["val_metric_std"].iloc[best_idx_a]
    num_features_a = report_a["num_features"].iloc[best_idx_a]

    # Best score from ShapRFECV WITH penalization
    shap_elimination = ShapRFECV(
        model=model, step=0.2, min_features_to_select=5, cv=5, scoring="f1", n_jobs=5, verbose=1
    )
    report_b = shap_elimination.fit_compute(X_train, y_train, shap_variance_penalty_factor=0.5, approximate=False)
    best_idx_b = get_best_idx(report_b)
    best_score_b = report_b["val_metric_mean"].iloc[best_idx_b]
    std_b = report_b["val_metric_std"].iloc[best_idx_b]
    num_features_b = report_b["num_features"].iloc[best_idx_b]

    results.append(
        [best_score_a, std_a, num_features_a, best_score_b, std_b, num_features_b, n_samples, n_features, n_informative]
    )

    results_df = pd.DataFrame(
        results,
        columns=[
            "best_score_a",
            "std_a",
            "num_features_a",
            "best_score_b",
            "std_b",
            "num_features_b",
            "n_samples",
            "n_features",
            "n_informative",
        ],
    )

# Show results
results_df

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

Feature Elimination:   0%|          | 0/195 [00:00<?, ?it/s]

,best_score_a,std_a,num_features_a,best_score_b,std_b,num_features_b,n_samples,n_features,n_informative
0,0.676692,0.072457,103,0.676692,0.072457,103,488,200,198
1,0.653939,0.033657,103,0.653939,0.033657,103,154,200,152
2,0.677267,0.051826,128,0.677267,0.051826,128,288,200,65
3,0.697027,0.060790,128,0.697027,0.060790,128,339,200,146
4,0.679644,0.094351,160,0.679644,0.094351,160,234,200,139